#!/bin/bash

echo "🔐 GitHub Authentication Setup"
echo "=============================="
echo ""
echo "Option 1: Web Browser Login (Easiest)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ gh auth login"
echo ""
echo "When prompted:"
echo "  What account do you want to log into? → GitHub.com"
echo "  What is your preferred protocol? → HTTPS"
echo "  Authenticate Git with your GitHub credentials? → Y"
echo "  How would you like to authenticate? → Paste an authentication token"
echo ""
echo "Then create a token at:"
echo "  https://github.com/settings/tokens/new"
echo ""
echo "Or run full auth:"
echo ""
echo "$ gh auth login --web"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 2: Using Personal Access Token"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to: https://github.com/settings/tokens/new"
echo "2. Name it: PrimeAI"
echo "3. Scopes needed: repo, admin:repo_hook"
echo "4. Generate token"
echo "5. Copy the token"
echo "6. Run: gh auth login"
echo "7. Select: Paste an authentication token"
echo "8. Paste your token"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press ENTER to start GitHub CLI authentication..."
gh auth login
